from . import kpi_goal
from . import kpi_hr_evaluation
from . import kpi_grade
from . import kpi_group_position
from . import kpi_level
from . import kpi_period
from . import department_kpi
from . import annual_kpi
from . import kpi_template
from . import hr_employee
from . import res_config_settings
from . import salary_calculate
from . import bonus_calculate
