{
    "name": "YKK - KPI Management",
    "summary": "KPI evaluation and allocation management for YKK",
    "version": "18.0.1.0.0",
    "category": "Human Resources",
    "author": "YKK",
    "license": "LGPL-3",
    "depends": [
        "base",
        "hr",
        "mail",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "data/decimal_precision_data.xml",
        "data/salary_calculate_data.xml",
        "data/bonus_calculate_data.xml",
        "views/menus.xml",
        "views/department_kpi_views.xml",
        "views/annual_kpi_views.xml",
        "views/kpi_goal_views.xml",
        "views/kpi_hr_evaluation_views.xml",
        "views/kpi_grade_views.xml",
        "views/kpi_group_position_views.xml",
        "views/kpi_level_views.xml",
        "views/kpi_period_views.xml",
        "views/kpi_template_views.xml",
        "views/salary_calculate_views.xml",
        "views/bonus_calculate_views.xml",
        "views/hr_views.xml",
        "views/hr_employee_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "application": True,
    "installable": True,
}
