{
    "name": "YKK - KPI Management",
    "summary": "KPI evaluation and allocation management for YKK",
    "version": "18.0.1.0.0",
    "category": "Human Resources",
    "author": "YKK",
    "license": "LGPL-3",
    "depends": [
        "base",
        "hr",
        "mail",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "data/decimal_precision_data.xml",
        "data/ir_sequence_data.xml",
        "data/running_sequence_data.xml",
        "data/salary_calculate_data.xml",
        "data/bonus_calculate_data.xml",
        "views/menus.xml",
        "views/department_kpi_views.xml",
        "views/department_kpi_update_views.xml",
        "views/annual_kpi_views.xml",
        "views/kpi_goal_views.xml",
        "views/kpi_hr_evaluation_views.xml",
        "views/kpi_grade_views.xml",
        "views/kpi_group_position_views.xml",
        "views/kpi_level_views.xml",
        "views/kpi_period_views.xml",
        "views/kpi_template_views.xml",
        "views/salary_calculate_views.xml",
        "views/bonus_calculate_views.xml",
        "views/relative_adjustment_group_views.xml",
        "views/kpi_grade_extend_views.xml",
        "views/hr_views.xml",
        "views/hr_employee_views.xml",
        "views/res_config_settings_views.xml",
        "views/kpi_adjustment_views.xml",
        "views/kpi_grade_history_views.xml",
        "views/adjustment_integration_views.xml",
        "views/adjustment_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ykk_kpi_management/static/src/scss/grade_grid.scss",
            "ykk_kpi_management/static/src/scss/grade_board.scss",
            "ykk_kpi_management/static/src/js/grade_grid_field.js",
            "ykk_kpi_management/static/src/js/grade_board_field.js",
            "ykk_kpi_management/static/src/xml/grade_grid_field.xml",
            "ykk_kpi_management/static/src/xml/grade_board_field.xml",
        ],
    },
    "application": True,
    "installable": True,
}
