from . import kpi_goal
from . import kpi_hr_evaluation
from . import kpi_grade
from . import kpi_group_position
from . import kpi_level
from . import kpi_period
from . import sequence_setting
from . import department_kpi
from . import department_kpi_update
from . import annual_kpi
from . import kpi_template
from . import running_sequence
from . import kpi_employee_history
from . import hr_employee
from . import res_config_settings
from . import salary_calculate
from . import bonus_calculate
from . import relative_adjustment_group
from . import kpi_grade_extend
from . import kpi_grade_history
from . import kpi_adjustment
from . import adjustment_integration
from . import import_tiger_soft
from . import template_document
from . import department_bell_curve
